name: pgs_health
description: Cotizador de Seguros.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+21

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  #global_configuration: ^1.4.0
  loading_animations: "^2.0.0"
  url_launcher: ^4.2.0+3
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  material_design_icons_flutter: 3.2.4595
  # keyboard_visibility: ^[CURRENT VERSION NUMBER]
  cached_network_image: ^2.0.0-rc

  flutter_keyboard_visibility: ^0.7.0
  intl: ">=0.14.0"
  grouped_buttons: ^1.0.4
  flutter_launcher_icons: "^0.7.4"
  # flutter_launch: ^0.2.0
  share: ^0.6.3+1
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.12.10
  flutter_statusbarcolor: ^0.2.3
  apple_sign_in: ^0.1.0
  flutter_secure_storage: ^3.3.1+1
  before_after: ^2.0.1
  firebase_crashlytics: ^0.1.2+5
  firebase_analytics: ^5.0.11


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # - ./assets/images/screen1.png
    # - ./assets/images/screen2.png
    # - ./assets/images/screen3.png
    # - ./assets/images/screen2.jpg
    - ./assets/images/drawer1.jpg
    - ./assets/images/logo.png
    - ./assets/images/logos/Sin-fondo-(4).png
    - ./assets/images/logos/Sin-fondo-(1).png
    - ./assets/images/logos/logo-ini.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Georgia
      fonts:
        - asset: ./fonts/georgia/Georgia.ttf
        - asset: ./fonts/georgia/Georgia-Italic.ttf
        - asset: ./fonts/georgia/Georgia-Bold.ttf
          # weight: 700
    - family: Vaud
      fonts:
        - asset: ./fonts/vaud/Vaud.ttf
        - asset: ./fonts/vaud/Vaud-Italic.ttf
        - asset: ./fonts/vaud/Vaud-Bold.ttf

flutter_icons:
  android: "launcher_icon" 
  ios: true
  # android: true
  image_path: "./assets/icon/icon.png"